### ISSUE TITLE
BIND provider as target?

### ISSUE THREAD

**Issue by kabenin** [octodns/octodns-bind#40]
Hello,
I have a use case where I want to get BIND zonefiles out of my OctoDNS configuration. It looks like octodns-bind package has BIND files as a source only. I'm curious: why is that? My scenario is not something people need, or are there other reasons for that?

Any inside would help! Thank you!

**Comment by ross** [comment]
> I'm curious: why is that?

No specific reason afaik, just that no one who's needed it and coded it up. Probably wouldn't be too hard to update the source to a provider (read and write,) but I've never looked into it. PRs welcome and otherwise it can get put onto the never ending TODO list. 

P. S. Moving this to https://github.com/octodns/octodns-bind since it's directly related to that provider.

**Comment by yzguy** [comment]
https://github.com/octodns/octodns/issues/254

It's not the hardest thing, but it's a bit weird because there is some info you have to provide, eg NS records, SOA record things, handle serial, etc. Just never got to it.

**Comment by ross** [comment]
> It's not the hardest thing, but it's a bit weird because there is some info you have to provide, eg NS records, SOA record things, handle serial, etc. Just never got to it.

i actually threw together something yesterday while killing time watching stuff. it's probably 75% of the way there. will push it up when i get it completed at some point.

**Comment by kabenin** [comment]
Amazing, @ross , thanks a lot for working on this!
